name: Tests

on:
  pull_request:
  push:
    branches: [master, main]
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  shell:
    uses: cgraf78/actions/.github/workflows/shell-ci.yml@1675121b79a8c194816606a74b21920f4a402592
    with:
      matrix-set: full
      profiles: base,shellcheck,tmux
      test-command: test/run
