name: Tests

on:
  pull_request:
  push:
    branches: [master, main]
  schedule:
    - cron: "7 9 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  shell:
    uses: cgraf78/actions/.github/workflows/shell-ci.yml@fb1777c6f248ece2ed02c8cb6d82533d011d3218
    with:
      matrix-set: full
      profiles: base,tmux
      shellcheck-inventory-path: .github/shellcheck-files.txt
      test-command: TMUX_TOOLS_SKIP_SHELLCHECK=1 test/run
